debian/bug/boinc-client/script      usr/share/bug/boinc-client
debian/conffiles/*                  etc/boinc-client
debian/extra/bash/*                 usr/share/bash-completion/completions
debian/extra/udev-cpu_share         usr/share/boinc-client
debian/extra/update-boinc-applinks  usr/bin
usr/bin/boinc
usr/bin/boinccmd
usr/bin/switcher                    usr/lib/boinc-client
usr/share/locale/*/LC_MESSAGES/BOINC-Client.mo
